@version: 4.0

source s_tcp {
    tcp(port(514) max-connections(100));
};

destination d_file {
    file("/var/log/syslog-ng/npm-proxy.log" template("${ISODATE} ${HOST} ${PROGRAM}: ${MSG}\n"));
};

log {
    source(s_tcp);
    destination(d_file);
};
